package com.phoneagent.app

import android.app.Application
import com.phoneagent.data.ExtensionEntity
import com.phoneagent.data.McpServerEntity
import com.phoneagent.data.PhoneAgentDatabase
import com.phoneagent.dsh.DshRuntimeProvisioner
import java.io.File
import java.security.MessageDigest
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.put

/** Migrates sai's reviewed Skills and MCP rows into DSH's native registries. */
class DshExtensionSynchronizer(
    application: Application,
    private val database: PhoneAgentDatabase,
    provisioner: DshRuntimeProvisioner,
) {
    private val mutex = Mutex()
    private val json = Json { ignoreUnknownKeys = true }
    private val extensionRoot = File(application.filesDir, "extensions")
    private val dshHome = provisioner.home
    private val skillsRoot = File(dshHome, "skills")
    private val managedSkillsIndex = File(dshHome, "sai-managed-skills.txt")
    private val mcpPatch = File(dshHome, "sai-extensions.cordis.patch.yml")
    private val diagnostics = File(dshHome, "sai-extension-sync-errors.txt")

    suspend fun syncNow() = withContext(Dispatchers.IO) {
        mutex.withLock {
            dshHome.mkdirs()
            val enabled = database.dao().extensions().filter(ExtensionEntity::enabled)
            syncSkills(enabled.filter { it.kind.equals("SKILL", true) })
            syncMcp(database.dao().mcpServers().filter(McpServerEntity::enabled))
        }
    }

    private fun syncSkills(skills: List<ExtensionEntity>) {
        skillsRoot.mkdirs()
        val previous = managedSkillsIndex.takeIf(File::isFile)?.readLines()?.filter(String::isNotBlank).orEmpty().toSet()
        val current = linkedSetOf<String>()
        val errors = mutableListOf<String>()
        skills.forEach { extension ->
            val sourceVersion = extension.version.ifBlank { extension.sourceDigest.take(12) }
            val source = File(extensionRoot, "${safeInstallId(extension.id)}/$sourceVersion").canonicalFile
            val targetName = managedSkillName(extension.id)
            val target = File(skillsRoot, targetName).canonicalFile
            runCatching {
                require(source.isDirectory && source.toPath().startsWith(extensionRoot.canonicalFile.toPath())) {
                    "已安装文件不存在"
                }
                require(File(source, "SKILL.md").isFile) { "缺少 SKILL.md" }
                val temporary = File(skillsRoot, ".$targetName.sai-tmp").canonicalFile
                require(temporary.toPath().startsWith(skillsRoot.canonicalFile.toPath())) { "Skill 同步路径越界" }
                temporary.deleteRecursively()
                check(source.copyRecursively(temporary, overwrite = true)) { "复制 Skill 失败" }
                target.deleteRecursively()
                check(temporary.renameTo(target) || temporary.copyRecursively(target, overwrite = true).also { temporary.deleteRecursively() }) {
                    "提交 Skill 失败"
                }
                current += targetName
            }.onFailure { errors += "${extension.name}: ${it.message}" }
        }
        (previous - current).forEach { stale ->
            val target = File(skillsRoot, stale).canonicalFile
            if (target.toPath().startsWith(skillsRoot.canonicalFile.toPath())) target.deleteRecursively()
        }
        writeAtomic(managedSkillsIndex, current.joinToString("\n", postfix = if (current.isEmpty()) "" else "\n"))
        writeDiagnostics(errors)
    }

    private fun syncMcp(servers: List<McpServerEntity>) {
        val errors = mutableListOf<String>()
        val rows = servers.mapNotNull { server ->
            runCatching { mcpRow(server) }.onFailure { errors += "${server.displayName}: ${it.message}" }.getOrNull()
        }
        val body = if (rows.isEmpty()) "[]\n" else buildString {
            append("# Generated by sai. Secrets must remain credential references, never literal values.\n")
            append("- insert:\n")
            rows.forEach { append(it) }
        }
        writeAtomic(mcpPatch, body)
        if (errors.isNotEmpty()) appendDiagnostics(errors)
    }

    private fun mcpRow(server: McpServerEntity): String {
        val source = json.parseToJsonElement(server.configJson).jsonObject
        val transport = (source["transport"] as? JsonPrimitive)?.contentOrNull?.uppercase() ?: "STREAMABLE_HTTP"
        val serverName = safeServerName(server.displayName, server.id)
        val config = when (transport) {
            "STDIO" -> {
                val commandValue = source["command"]
                val commandParts = when (commandValue) {
                    is JsonArray -> commandValue.mapNotNull { (it as? JsonPrimitive)?.contentOrNull }
                    is JsonPrimitive -> commandValue.content.split(Regex("\\s+")).filter(String::isNotBlank)
                    else -> emptyList()
                }
                require(commandParts.isNotEmpty()) { "stdio MCP 缺少命令" }
                buildJsonObject {
                    put("transport", "stdio")
                    put("serverName", serverName)
                    put("command", commandParts.first())
                    put("args", JsonArray(commandParts.drop(1).map(::JsonPrimitive)))
                    put("env", JsonObject(emptyMap()))
                    put("cwd", "/home/phoneagent")
                    put("toolCallTimeoutMs", 60_000)
                    put("failOnStartupError", false)
                }
            }
            "STREAMABLE_HTTP", "SSE" -> {
                val url = (source["url"] as? JsonPrimitive)?.contentOrNull
                require(url?.startsWith("https://") == true || url?.startsWith("http://") == true) { "HTTP MCP URL 无效" }
                require(source.keys.none { it.equals("headers", true) || it.contains("token", true) || it.contains("secret", true) }) {
                    "Header/令牌必须改用 Keystore 凭据引用"
                }
                buildJsonObject {
                    put("transport", "streamable-http")
                    put("serverName", serverName)
                    put("url", url!!)
                    put("headers", JsonObject(emptyMap()))
                    put("toolCallTimeoutMs", 60_000)
                    put("failOnStartupError", false)
                }
            }
            else -> error("不支持的 MCP transport：$transport")
        }
        val rowId = "sai-mcp-${serverName.lowercase()}"
        return "    - id: '$rowId'\n      name: '@deepseek-ai/dsh-mcp-client'\n      config: ${config}\n"
    }

    private fun writeDiagnostics(errors: List<String>) = writeAtomic(diagnostics, errors.joinToString("\n"))
    private fun appendDiagnostics(errors: List<String>) {
        val existing = diagnostics.takeIf(File::isFile)?.readText().orEmpty().trim()
        writeAtomic(diagnostics, (listOf(existing) + errors).filter(String::isNotBlank).distinct().joinToString("\n"))
    }

    private fun writeAtomic(target: File, contents: String) {
        target.parentFile?.mkdirs()
        val temporary = File(target.parentFile, "${target.name}.sai-tmp")
        temporary.writeText(contents, Charsets.UTF_8)
        temporary.setReadable(false, false); temporary.setReadable(true, true)
        temporary.setWritable(false, false); temporary.setWritable(true, true)
        check(temporary.renameTo(target) || temporary.copyTo(target, overwrite = true).let { temporary.delete(); true }) {
            "无法更新 ${target.name}"
        }
    }

    private fun safeInstallId(id: String) = id.replace(Regex("[^A-Za-z0-9._-]"), "_")
    private fun managedSkillName(id: String): String {
        val stem = safeInstallId(id).take(56).ifBlank { "skill" }
        return "$stem-${sha256(id).take(8)}"
    }
    private fun safeServerName(name: String, id: String): String {
        val stem = name.replace(Regex("[^A-Za-z0-9_-]"), "_").trim('_').take(20).ifBlank { "mcp" }
        return "${stem}_${sha256(id).take(7)}".take(32)
    }
    private fun sha256(value: String) = MessageDigest.getInstance("SHA-256")
        .digest(value.toByteArray()).joinToString("") { "%02x".format(it) }
}
